### ISSUE TITLE
Sorry, this account, device or location has been temporarily suspended

### ISSUE THREAD

**Issue by dipaadipati** [CLOEI/Mori#10]
Hi, i still dont know how to code in rust language but, i got suspended message every i am used 5+ legacy accounts, i think that not about my acc is suspended, but the device or location. I tried to use any vpn but it does not work, i know why this message come because an IP or a device information are noted by ubisoft as illegal account. I used Ubuntu Linux BTW, do you know what code should i edit then? or do you have other alternate to change my device or location information?
Thanks for the app btw

**Comment by genkuqq** [comment]
You don't need edit any code. Just use proxies for multiple accounts. Its gonna solve your problem. Also you don't need vpn if your clients connecting with proxies. You can find easily on google "Free proxies 2024" etc.

**Comment by CLOEI** [comment]
What @genkuqq said is true.
I added one more thing, @dipaadipati you could try to turn off and turn on your router again after 5 to 10 sec.
It should gain a new IP.
