### ISSUE TITLE
login update

### ISSUE THREAD

**Issue by bbangg** [CLOEI/Mori#14]
We are receiving random GrowIDs after logging in with legacy login mode. This must be fixed because accounts with these names are being banned regularly.

![image](https://github.com/user-attachments/assets/8cf7ced9-f51b-43ef-8d9a-39fe44c28023)

**Comment by CLOEI** [comment]
Hmm, it give us a random growid even when we use a legacy account?
That's interesting

**Comment by CLOEI** [comment]
![image](https://github.com/user-attachments/assets/d54b4416-65e1-4269-8bd8-d2d1fd364080)
Sniffed packet data for login process doesn't have aat string

**Comment by bbangg** [comment]
```
OnSendToServer: VariantList { variants: [String("OnSendToServer"), Signed(123), Signed(abc), Signed(xyz), String("213.179.209.184|0|..."), Signed(1), String("GrowIDHere")] }
```

aat|1 is working

**Comment by CLOEI** [comment]
Right, fixed thanks! also i updated the protocol too b320875
Please re-open if the issue still persist.
